#!/bin/csh

source /opt/ngat/etc/cshrc

source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/tcs_sim_setup

setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LIB_HOME

set NAME     = I
set PORT     = 4556
set ISSHOST  = localhost
set ISSPORT  = 7383
set MS       = 0.9
set DS       = 0.65
set MP       = 3

$JAVA  InstrumentControl --name $NAME --port $PORT --iss-host $ISSHOST --iss-port $ISSPORT --prefix "m" \
        --mean-seeing $MS --std-seeing $DS --mirror-port $MP >& ~/i.log

