#!/bin/csh

source /opt/ngat/etc/cshrc

source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/tcs_sim_setup


setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LIB_HOME

set NAME     = RINGO3
#set PORT     = 8283
set PORT     = 1112
set ISSHOST  = localhost
set ISSPORT  = 7383
set MS       = 0.7
set DS       = 0.35
set MP       = 4
$JAVA -Ddilate=10 InstrumentControl --name $NAME --port $PORT --iss-host $ISSHOST --iss-port $ISSPORT --prefix "def" \
        --mean-seeing $MS --std-seeing $DS --mirror-port $MP >& ~/ringo.log
