#!/bin/csh

source /opt/ngat/etc/cshrc

source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/tcs_sim_setup

setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LIB_HOME

set NAME     = RISE
set PORT     = 6777
set ISSHOST  = localhost
set ISSPORT  = 7383
set MS       = 1.5
set DS       = 0.45
set MP       = 1
$JAVA -Ddilate=10 InstrumentControl --name $NAME --port $PORT --iss-host $ISSHOST --iss-port $ISSPORT --prefix "q" \
        --mean-seeing $MS --std-seeing $DS --mirror-port $MP   >& ~/rise.log

