#!/bin/csh

# Starts up a ScheduleDespatcher and ExecutionUpdateManager

source /opt/ngat/etc/cshrc

source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/x_setup

java ngat.sms.test.StartExecutionManagerAndScheduler \
    --gls-host ltdev1 --gls-port 2731 \
    --bind-host localhost --base-host ltdev1 --comp-host ltdev1 \
    --lat 28.7 --long -150.0
